main: ru.enjoymine.CivCraft.Main
name: CivCraft
version: 1.0
commands:
  c:
    aliases: [civ, civilization]
  accept:
    aliases: [y, aye, yeah]
  deny:
    aliases: [n, not, reject]
  t:
    aliases: [town]

depend:
  - WorldEdit

permissions:
  cc.admin:
    description: "all plugin permissions"
  c.builder:
    description: "builder permissions"